// Generated by CoffeeScript 1.7.1
(function() {
  var nodeParser, should, _, _validParserResult;

  nodeParser = require("../lib/index");

  should = require("should");

  _ = require("underscore");

  describe("daily parse test", function() {
    it("should parse", function(done) {
      var url;
      url = "http://daily.zhihu.com/story/4131277";
      return nodeParser.parse(url, function(err, article) {
        should(err).not.exist;
        _validParserResult(article);
        return done();
      });
    });
    return it("should parse,too", function(done) {
      var url;
      url = "http://daily.zhihu.com/story/4130697";
      return nodeParser.parse(url, function(err, article) {
        should(err).not.exist;
        _validParserResult(article);
        return done();
      });
    });
  });

  _validParserResult = function(article) {
    should(article).be.exist;
    article.title.should.be.a.String.and.not.be.empty;
    article.question.should.be.a.String.and.not.be.empty;
    article.answers.should.be.an.Array;
    return article.answers.should.matchEach(function(ans) {
      var hasContent, validAuthor, validAuthorAbout, validAuthorName;
      validAuthor = ans.author.should.have.keys("name", "about");
      validAuthorName = ans.author.name.should.be.a.String.and.not.be.empty;
      validAuthorAbout = ans.author.about.should.be.a.String;
      hasContent = ans.content.should.be.a.String.and.not.be.empty;
      return validAuthor && validAuthorName && validAuthorAbout && hasContent;
    });
  };

}).call(this);

//# sourceMappingURL=daily.test.map
