// Generated by CoffeeScript 1.7.1
(function() {
  var nodeParser, should, _;

  nodeParser = require("../lib/index");

  should = require("should");

  _ = require("underscore");

  describe("parser test", function() {
    return it("should parser", function(done) {
      var url;
      url = "http://www.zhihu.com/question/23797702";
      console.dir(nodeParser);
      return nodeParser.parse(url, function(err, article) {
        should(err).not.exist;
        console.dir(article);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=parser.map
