// Generated by CoffeeScript 1.7.1
(function() {
  var nodeParser, should, _, _validParserResult;

  nodeParser = require("../lib/index");

  should = require("should");

  _ = require("underscore");

  describe("parser test", function() {
    it("should parser", function(done) {
      var url;
      url = "http://www.zhihu.com/question/23797702";
      return nodeParser.parse(url, function(err, article) {
        should(err).not.exist;
        _validParserResult(article);
        return done();
      });
    });
    return it("should parse ok", function(done) {
      var url;
      url = "http://www.zhihu.com/question/25066430";
      return nodeParser.parse(url, function(err, article) {
        should(err).not.exist;
        article.title.should.be.a.String.and.not.be.empty.and.be.exactly("被迫参加莫名其妙的亲戚聚会和人情往来，如何礼貌地打发时间？");
        _validParserResult(article);
        return done();
      });
    });
  });

  _validParserResult = function(article) {
    should(article).be.exist;
    article.question.should.be.a.String.and.not.be.empty;
    article.answers.should.be.an.Array;
    article.answers.should.matchEach(function(ans) {
      var hasContent, validAuthor, validAuthorAbout, validAuthorName;
      validAuthor = ans.author.should.have.keys("name", "about");
      validAuthorName = ans.author.name.should.be.a.String.and.not.be.empty;
      validAuthorAbout = ans.author.about.should.be.a.String;
      hasContent = ans.content.should.be.a.String.and.not.be.empty;
      return validAuthor && validAuthorName && validAuthorAbout && hasContent;
    });
    article.tags.should.be.an.Array;
    return article.tags.should.matchEach(function(tag) {
      return tag.should.be.a.String.and.not.be.empty;
    });
  };

}).call(this);

//# sourceMappingURL=question.test.map
