// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, request, util, _parseDaily, _parseQuestion;

  util = require("./util");

  request = require("request");

  cheerio = require("cheerio");


  /*
      zhihu parser
      @param {String} url
      @param {Function} cb callback function
   */

  exports.parse = function(url, cb) {
    if (url) {
      if (util.isZhihuDaily(url)) {
        return _parseDaily(url, cb);
      } else if (util.isZhihuQuestion(url)) {
        return _parseQuestion(url, cb);
      } else {
        return cb(new Error("url " + url + " isn't zhihu daily or zhihu question"));
      }
    } else {
      return cb(new Error("must have a url"));
    }
  };


  /*
      parse zhihu question
      @param {String} url
      @param {Function} cb callback function
   */

  _parseQuestion = function(url, cb) {
    if (util.isZhihuQuestion(url)) {
      return util.download(url, function(err, content) {
        var $, answers, answersArr, article, page, question, title;
        if (err) {
          return cb(err);
        } else {
          $ = cheerio.load(content);
          page = [];
          title = $('#zh-question-title').text().trim();
          question = $("#zh-question-detail").html().trim();
          page.push('<div>' + question + '</div>');
          page.push('<hr>');
          answersArr = [];
          answers = $('.zm-item-answer');
          answers.each(function() {
            var answerDetail, authorInfo, node;
            node = $(this);
            authorInfo = node.find('.zm-item-answer-author-wrap').text().trim();
            node.find('.toggle-expand').remove();
            answerDetail = node.find('.zm-editable-content');
            util.pullOutRealPath(answerDetail);
            util.trimAttrs(answerDetail);
            return answersarr.push({
              author: util.getAuthor(authorInfo),
              content: answerDetail.html().trim()
            });
          });
          article = {
            title: title,
            question: question,
            answers: answersArr
          };
          return cb(null, article);
        }
      });
    } else {
      return cb(new Error("url " + url + " isn't zhihu question page"));
    }
  };


  /*
      parse zhihu daily page
      @param {String} url
      @param {Function} cb callback function
   */

  _parseDaily = function(url, cb) {
    if (util.isZhihuDaily(url)) {
      return util.download(url, function(err, content) {
        var $, answers, answersArr, article, imgSrc, question, title;
        if (err) {
          return cb(err);
        } else {
          $ = cheerio.load(content);
          title = $('title').text();
          imgSrc = $('.img-wrap img').attr('src').trim();
          question = $('.question-title').text();
          answers = $('.answer');
          answersArr = [];
          answers.each(function() {
            var answerDetail, author, node;
            node = $(this);
            author = node.find('.meta').text();
            answerDetail = node.find('.content');
            solveHelper.zhihuImg(answerDetail);
            solveHelper.trimAttrs(answerDetail);
            return answersArr.push({
              author: util.getAuthor(author.trim()),
              content: answerDetail.html().trim()
            });
          });
          article = {
            title: title,
            question: question,
            image: imgSrc,
            answers: answersArr
          };
          return cb(null, article);
        }
      });
    } else {
      return cb(new Error("url " + url + " isn't zhihu daily page"));
    }
  };

}).call(this);

//# sourceMappingURL=index.map
