// Generated by CoffeeScript 1.7.1
(function() {
  var cheerio, request, util;

  util = require("./util");

  request = require("request");

  cheerio = require("cheerio");

  exports.parse = function(url, cb) {
    return util.download(url, function(err, content) {
      var $, answers, answersArr, article, page, question, title;
      if (err) {
        return cb(err);
      } else {
        $ = cheerio.load(content);
        page = [];
        title = $('#zh-question-title').text().trim();
        question = $("#zh-question-detail").html().trim();
        page.push('<div>' + question + '</div>');
        page.push('<hr>');
        answersArr = [];
        answers = $('.zm-item-answer');
        answers.each(function() {
          var answerDetail, authorInfo, node;
          node = $(this);
          authorInfo = node.find('.zm-item-answer-author-wrap').text().trim();
          node.find('.toggle-expand').remove();
          answerDetail = node.find('.zm-editable-content');
          util.pullOutRealPath(answerDetail);
          util.trimAttrs(answerDetail);
          return answersArr.push({
            author: util.getAuthor(authorInfo),
            content: answerDetail.html().trim()
          });
        });
        article = {
          title: title,
          question: question,
          answers: answersArr
        };
        return cb(null, article);
      }
    });
  };

}).call(this);

//# sourceMappingURL=index.map
